Add background on Central backups
getodk/docs pull request #1263
Opened 2020-09-25 00:25 UTC by lognaturel

We've gotten various questions about Central backups and where they send data (e.g. https://github.com/getodk/central/issues/167). This PR clarifies that managing external backups is a possibility and may be a better option for a lot of folks. 

This PR also adds a note about data restores having to go on the same Central version the backup was made from in response to https://forum.getodk.org/t/expiry-warning-but-ssl-test-and-check-ssl-show-otherwise/29466. I don't think this is precisely true -- I believe it would be ok to restore to an updated Central version but Central would need to be rebuilt to trigger migrations. It seems simpler to say the restore should happen on the same Central version but I could be convinced to change it.

2020-10-02 18:13 UTC, yanokwa requested changes

2020-10-02 18:13 UTC, yanokwa commented on odk1-src/central-backup.rst
> +Having a data backup strategy is a critical part of running a web service like ODK Central. Backups should go to a system in a different physical location from where Central is installed in order to
"of the PostgreSQL database that contains all Central's data."

Basically, we need a lightweight way of saying that everything that is in Central is in that database. That is, there is nothing else important on the filesystem.

2020-10-02 18:13 UTC, yanokwa commented on odk1-src/central-backup.rst
> +Restoring a backup to an ODK Central instance will entirely replace all of its data with the backup. Please be very sure you are restoring to the right place with the right backup snapshot before pro
Too many ODK Centrals. Just Central is fine.

2020-10-02 20:12 UTC, lognaturel commented
Regarding versions, maybe what we should say is if things don't work, do `docker-compose stop`, `docker-compose build`, `docker-compose up -d`. I believe that would run migrations. @issa-tseng?

2020-10-07 13:04 UTC, yanokwa approved these changes

2020-10-07 13:57 UTC, merged