Add background audio documentation
getodk/docs pull request #1327
Opened 2021-02-17 02:06 UTC by lognaturel

To be shipped with Collect v1.30

I recommend looking at the two commits separately. There's a little bit of redundancy with the foreground audio section but I couldn't find smooth ways to link between them. This feels ok and I think it's fine if the wording ends up deviating a little bit.

TODO:
- Basic sample form
- Examples of introduction screens. I'd like to do one that's just informational, one that asks for consent and one that allows the respondent to pick topics they're comfortable discussing while being recorded. I'm hesitating between attaching XLSX files and putting the form defs inline but collapsed by default. I'd love thoughts on that or other options!

2021-02-17 14:56 UTC, seadowg commented
> Any screenshot needed? I've gone back and forth on adding one of the top bar.

Yeah, not sure. I think you've done a good job of explaining it here. There's not a lot of UI to give examples of, so we probably don't need them.

> I'm hesitating between attaching XLSX files and putting the form defs inline but collapsed by default. I'd love thoughts on that or other options!

Do you mean linking to an example or having the form defs inline? I think for this it'd be fine to have it inline seeing as it's just one line.

2021-02-17 14:56 UTC, seadowg requested changes

2021-02-17 14:56 UTC, seadowg commented on src/form-question-types.rst
> +Before adding background audio recording to your form, make sure that you have a plan for following local laws around audio recording. We generally recommend including a note at the beginning of the
This and the next paragraph feel like they might suit being a "tip" right? I feel like this whole section is quite long, and it'd be good to break up the opinionated/advisory stuff from the core info.

2021-02-17 14:56 UTC, seadowg commented on src/form-question-types.rst
> +There is an override available to data collectors when recording might compromise safety or when consent to record can't be obtained but it's still important to capture some data. When the audio reco
This could maybe live in a sub-heading ("Enumerator override" for instance).

2021-02-17 14:56 UTC, seadowg commented on src/form-question-types.rst
> +In some rare cases such as the device running out of space, the recording may complete successfully but not be attached to the form. If this happens, the recording may be available in the ``recording
Maybe this could be a warning? Or we could pull it out as a subsection of the recording question section and link to it here.

2021-02-17 16:55 UTC, lognaturel commented
> seeing as it's just one line.

I'm talking about the intro screen examples. Those are going to be big. I'm now thinking they're likely more usable as XLSX.

2021-02-17 17:48 UTC, seadowg commented
@lognaturel gah sorry yeah that makes sense. Yes I agree it'd be better as an example XLSX.

2021-02-23 05:20 UTC, lognaturel commented
Thanks! I added some headings as suggested and did a little bit of reorganization that I think make things flow better.

I propose we go with this for now and file an issue to add introduction examples and make other improvements.

2021-02-23 09:55 UTC, seadowg commented
@lognaturel agreed. I think the headings really help!

2021-02-23 09:55 UTC, seadowg approved these changes

2021-02-23 17:21 UTC, merged